CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    BIO VARCHAR(150),
    AVATAR_URL VARCHAR(50) DEFAULT 'DEFAULT_AVATAR.png',
    IS_PRIVATE BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IMAGE_POSTS(
    ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES TO USERS(ID) ON DELETE CASCADE,
    TITLE TEXT,
    IMAGE_URL VARCHAR(50),
    LIKES_COUNT INT DEFAULT 0,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VIDEO_POSTS(
    ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES TO USERS(ID) ON DELETE CASCADE,
    TITLE TEXT,
    VIDEO_URL VARCHAR(50),
    LIKES_COUNT INT DEFAULT 0,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IMAGE_LIKES(
    USER_ID REFERENCES TO USERS(ID) ON DELETE CASCADE,
    POST_ID REFERENCES TO IMAGE_POSTS(ID) ON DELETE CASCADE,
    PRIMARY KEY (USER_ID, POST_ID)
);

CREATE TABLE VIDEO_LIKES(
    USER_ID REFERENCES TO USERS(ID) ON DELETE CASCADE,
    POST_ID REFERENCES TO VIDEO_POSTS(ID) ON DELETE CASCADE,
    PRIMARY KEY (USER_ID, POST_ID)
);

CREATE TABLE IMAGE_COMMENTS(
    ID SERIAL PRIMARY KEY,
    USER_ID REFERENCES TO USERS(ID) ON DELETE CASCADE,
    POST_ID REFERENCES TO IMAGE_POSTS(ID) ON DELETE CASCADE,
    PARENT_ID REFERENCES TO IMAGE_COMMENTS(ID) ON DELETE CASCADE,
    CONTENT TEXT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VIDEO_COMMENTS(
    ID SERIAL PRIMARY KEY,
    USER_ID REFERENCES TO USERS(ID) ON DELETE CASCADE,
    POST_ID REFERENCES TO VIDEO_POSTS(ID) ON DELETE CASCADE,
    PARENT_ID REFERENCES TO VIDEO_COMMENTS(ID) ON DELETE CASCADE,
    CONTENT TEXT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FOLLOWS(
    FOLLOWER_ID REFERENCES TO USERS(ID) ON DELETE CASCADE,
    FOLLOWING_ID REFERENCES TO USERS(ID) ON DELETE CASCADE,
    STATUS VARCAR(20) DEFAULT 'ACCEPTED',
    PRIMARY KEY (FOLLOWER_ID, FOLLOWING_ID)
);

CREATE TABLE USERS(
    
);